/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author movvakodandram
 */
public class CommunityAdmin extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdmin
     */
    public CommunityAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        addComm = new javax.swing.JButton();
        editComm = new javax.swing.JButton();
        addHos = new javax.swing.JButton();
        editHos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        addComm.setText("ADD COMMUNITY");
        addComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommActionPerformed(evt);
            }
        });

        editComm.setText("EDIT COMMUNITY");
        editComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCommActionPerformed(evt);
            }
        });

        addHos.setText("ADD HOSPITAL");
        addHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHosActionPerformed(evt);
            }
        });

        editHos.setText("EDIT HOSPITAL");
        editHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addComm, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(editComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addHos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editHos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(addComm)
                .addGap(48, 48, 48)
                .addComponent(editComm)
                .addGap(48, 48, 48)
                .addComponent(addHos)
                .addGap(43, 43, 43)
                .addComponent(editHos)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        splitPane3.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        splitPane3.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane3)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommActionPerformed
        // TODO add your handling code here:
        AddCommunity addcomm= new AddCommunity();
        splitPane3.setRightComponent(addcomm);

    }//GEN-LAST:event_addCommActionPerformed

    private void editCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCommActionPerformed
        // TODO add your handling code here:
        EditCommunity editcomm= new EditCommunity();
        splitPane3.setRightComponent(editcomm);
    }//GEN-LAST:event_editCommActionPerformed

    private void addHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHosActionPerformed
        // TODO add your handling code here:
        AddHospital addhosp= new AddHospital();
        splitPane3.setRightComponent(addhosp);

    }//GEN-LAST:event_addHosActionPerformed

    private void editHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHosActionPerformed
        // TODO add your handling code here:
        EditHospital edithosp= new EditHospital();
        splitPane3.setRightComponent(edithosp);
    }//GEN-LAST:event_editHosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComm;
    private javax.swing.JButton addHos;
    private javax.swing.JButton editComm;
    private javax.swing.JButton editHos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitPane3;
    // End of variables declaration//GEN-END:variables
}
