/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.CommunityData;
import model.CommunityHistory;

/**
 *
 * @author movvakodandram
 */
public class AddCommunity extends javax.swing.JPanel {

    /**
     * Creates new form AddCommunity
     */
    CommunityHistory comHis;
    
    public AddCommunity(CommunityHistory comHis) {
        initComponents();
        this.comHis=comHis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommName = new javax.swing.JLabel();
        lblCommZip = new javax.swing.JLabel();
        txtCommName = new javax.swing.JTextField();
        txtCommZip = new javax.swing.JTextField();
        submitAddComm = new javax.swing.JButton();

        lblCommName.setText("Community Name");

        lblCommZip.setText("Zip Code");

        txtCommName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommNameActionPerformed(evt);
            }
        });

        txtCommZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommZipActionPerformed(evt);
            }
        });

        submitAddComm.setText("SUBMIT");
        submitAddComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddCommActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitAddComm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCommZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCommName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCommZip, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txtCommName))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommName)
                    .addComponent(txtCommName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommZip)
                    .addComponent(txtCommZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(submitAddComm)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommNameActionPerformed

    private void txtCommZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommZipActionPerformed

    private void submitAddCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddCommActionPerformed
        // TODO add your handling code here:
            if(txtCommName.getText().equals("")||txtCommZip.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the information");
            
        }
        else if(validateData()){
            String commName=txtCommName.getText();
            String commZip=txtCommZip.getText();
           
           
            
            CommunityData cd= comHis.addNewData();
            cd.setcName(commName);
            cd.setZipCode(commZip);
          
          
            
            JOptionPane.showMessageDialog(this,"New Community Created");
            txtCommName.setText("");
            txtCommZip.setText("");
 
        }

    }//GEN-LAST:event_submitAddCommActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCommName;
    private javax.swing.JLabel lblCommZip;
    private javax.swing.JButton submitAddComm;
    private javax.swing.JTextField txtCommName;
    private javax.swing.JTextField txtCommZip;
    // End of variables declaration//GEN-END:variables

    private boolean validateData() {

        if (txtCommName.getText().length() < 2 || !txtCommName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper community name");
            return false;
        }
          
        if (txtCommZip.getText().length() < 2 || !txtCommZip.getText().matches("^[0-9]{5}(?:-[0-9]{4})?$")) {
            JOptionPane.showMessageDialog(this, "Enter proper zipcode");
            return false;
        }
  
        return true;
        
        
    }
}
