/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author movvakodandram
 */
public class AddDoctor extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctor
     */
    public AddDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrName = new javax.swing.JLabel();
        lblDrSpecialisation = new javax.swing.JLabel();
        txtDrName = new javax.swing.JTextField();
        txtDrSpecislisation = new javax.swing.JTextField();
        addDrSubmit = new javax.swing.JButton();
        lblHname = new javax.swing.JLabel();
        txtHName = new javax.swing.JTextField();

        lblDrName.setText("Doctor Name");

        lblDrSpecialisation.setText("Specialisation");

        txtDrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrNameActionPerformed(evt);
            }
        });

        txtDrSpecislisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrSpecislisationActionPerformed(evt);
            }
        });

        addDrSubmit.setText("SUBMIT");
        addDrSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrSubmitActionPerformed(evt);
            }
        });

        lblHname.setText("Hospital Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDrSubmit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrName)
                            .addComponent(lblDrSpecialisation)
                            .addComponent(lblHname))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDrName)
                            .addComponent(txtDrSpecislisation)
                            .addComponent(txtHName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrName)
                    .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrSpecialisation)
                    .addComponent(txtDrSpecislisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHname)
                    .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addDrSubmit)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrNameActionPerformed

    private void txtDrSpecislisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrSpecislisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrSpecislisationActionPerformed

    private void addDrSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDrSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrSubmit;
    private javax.swing.JLabel lblDrName;
    private javax.swing.JLabel lblDrSpecialisation;
    private javax.swing.JLabel lblHname;
    private javax.swing.JTextField txtDrName;
    private javax.swing.JTextField txtDrSpecislisation;
    private javax.swing.JTextField txtHName;
    // End of variables declaration//GEN-END:variables
}
