/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.DoctorData;
import model.DoctorHistory;

/**
 *
 * @author movvakodandram
 */
public class AddDoctor extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctor
     */
    DoctorHistory drHis;
    
    public AddDoctor(DoctorHistory drHis) {
        initComponents();
        this.drHis=drHis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrName = new javax.swing.JLabel();
        lblDrSpecialisation = new javax.swing.JLabel();
        txtDrName = new javax.swing.JTextField();
        txtDrSpecialisation = new javax.swing.JTextField();
        addDrSubmit = new javax.swing.JButton();
        lblHname = new javax.swing.JLabel();
        txtHName = new javax.swing.JTextField();

        lblDrName.setText("Doctor Name");

        lblDrSpecialisation.setText("Specialisation");

        txtDrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrNameActionPerformed(evt);
            }
        });

        txtDrSpecialisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrSpecialisationActionPerformed(evt);
            }
        });

        addDrSubmit.setText("SUBMIT");
        addDrSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrSubmitActionPerformed(evt);
            }
        });

        lblHname.setText("Hospital Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDrSubmit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrName)
                            .addComponent(lblDrSpecialisation)
                            .addComponent(lblHname))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDrName)
                            .addComponent(txtDrSpecialisation)
                            .addComponent(txtHName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrName)
                    .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrSpecialisation)
                    .addComponent(txtDrSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHname)
                    .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addDrSubmit)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrNameActionPerformed

    private void txtDrSpecialisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrSpecialisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrSpecialisationActionPerformed

    private void addDrSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrSubmitActionPerformed
        // TODO add your handling code here:
          if(txtDrName.getText().equals("")||txtDrSpecialisation.getText().equals("")||txtHName.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Please fill all the information");
            
        }
        else if(validateData()){
            String drName=txtDrName.getText();
            String special=txtDrSpecialisation.getText();
            String hName=txtHName.getText();
           
           
            
            DoctorData dd= drHis.addNewData();
            dd.setDrName(drName);
            dd.setDrSpec(special);
            dd.setHospitalName(hName);
          
          
            
            JOptionPane.showMessageDialog(this,"New Doctor Created");
            txtDrName.setText("");
            txtDrSpecialisation.setText("");
            txtHName.setText("");
 
        }


    }//GEN-LAST:event_addDrSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrSubmit;
    private javax.swing.JLabel lblDrName;
    private javax.swing.JLabel lblDrSpecialisation;
    private javax.swing.JLabel lblHname;
    private javax.swing.JTextField txtDrName;
    private javax.swing.JTextField txtDrSpecialisation;
    private javax.swing.JTextField txtHName;
    // End of variables declaration//GEN-END:variables

    private boolean validateData() {
        if (txtDrName.getText().length() < 2 || !txtDrName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper Name");
            return false;
        }
        
        if (txtDrSpecialisation.getText().length() < 2 || !txtDrSpecialisation.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper specialisation");
            return false;
        }
          
        if (txtHName.getText().length() < 2 || !txtHName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper hospital name");
            return false;
        }
  
        return true;
        
    }
}
