/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.HospitalData;
import model.HospitalHistory;

/**
 *
 * @author movvakodandram
 */
public class AddHospital extends javax.swing.JPanel {

    /**
     * Creates new form AddHospital
     */
    HospitalHistory hosHis;
    public AddHospital(HospitalHistory hosHis) {
        initComponents();
        this.hosHis=hosHis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHsptlName = new javax.swing.JLabel();
        txtHsptlName = new javax.swing.JTextField();
        btnAddHsptl = new javax.swing.JButton();
        txtCommZipHsptl = new javax.swing.JTextField();
        lblCommNameHsptl = new javax.swing.JLabel();
        lblCommZipHsptl = new javax.swing.JLabel();
        txtCommNameHsptl = new javax.swing.JTextField();

        lblHsptlName.setText("Hospital Name");

        btnAddHsptl.setText("SUBMIT");
        btnAddHsptl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHsptlActionPerformed(evt);
            }
        });

        txtCommZipHsptl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommZipHsptlActionPerformed(evt);
            }
        });

        lblCommNameHsptl.setText("Community Name");

        lblCommZipHsptl.setText("Zip Code");

        txtCommNameHsptl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommNameHsptlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddHsptl)
                        .addGap(357, 357, 357))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHsptlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCommZipHsptl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCommNameHsptl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCommNameHsptl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtHsptlName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCommZipHsptl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHsptlName)
                    .addComponent(txtHsptlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommNameHsptl)
                    .addComponent(txtCommNameHsptl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommZipHsptl)
                    .addComponent(txtCommZipHsptl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAddHsptl)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommZipHsptlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommZipHsptlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommZipHsptlActionPerformed

    private void txtCommNameHsptlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommNameHsptlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommNameHsptlActionPerformed

    private void btnAddHsptlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHsptlActionPerformed
        // TODO add your handling code here:
            if(txtHsptlName.getText().equals("")||txtCommNameHsptl.getText().equals("")||txtCommZipHsptl.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the information");
            
        }
        else if(validateData()){
            String hName=txtHsptlName.getText();
            String commName1=txtCommNameHsptl.getText();
            String commZip1=txtCommZipHsptl.getText();       
            HospitalData hd= hosHis.addNewData();
            hd.setHosName(hName);
            hd.setCommName(commName1);
            hd.setZip(commZip1);
    
            JOptionPane.showMessageDialog(this,"New Hospital Created");
            txtHsptlName.setText("");
            txtCommNameHsptl.setText("");
            txtCommZipHsptl.setText("");
 
        }


    }//GEN-LAST:event_btnAddHsptlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHsptl;
    private javax.swing.JLabel lblCommNameHsptl;
    private javax.swing.JLabel lblCommZipHsptl;
    private javax.swing.JLabel lblHsptlName;
    private javax.swing.JTextField txtCommNameHsptl;
    private javax.swing.JTextField txtCommZipHsptl;
    private javax.swing.JTextField txtHsptlName;
    // End of variables declaration//GEN-END:variables

    private boolean validateData() {
        
        if (txtHsptlName.getText().length() < 2 || !txtHsptlName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper community name");
            return false;
        }
        
        if (txtCommNameHsptl.getText().length() < 2 || !txtCommNameHsptl.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper community name");
            return false;
        }
          
        if (txtCommZipHsptl.getText().length() < 2 || !txtCommZipHsptl.getText().matches("^[0-9]{5}(?:-[0-9]{4})?$")) {
            JOptionPane.showMessageDialog(this, "Enter proper zipcode");
            return false;
        }
  
        return true;
        
        
    }
}
