/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.MedicalSystem;
import model.PersonData;
import model.PersonHistory;

/**
 *
 * @author movvakodandram
 */
public class AddPerson extends javax.swing.JPanel {

    /**
     * Creates new form AddPerson
     */
    
    MedicalSystem med;
    PersonHistory perHis;
    
    public AddPerson(PersonHistory perHis) {
        initComponents();
        this.perHis=perHis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonID = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmergency = new javax.swing.JLabel();
        submitAddPerson = new javax.swing.JButton();
        txtPersonID = new javax.swing.JTextField();
        txtPersonName = new javax.swing.JTextField();
        txtPersonAge = new javax.swing.JTextField();
        txtPersonPhone = new javax.swing.JTextField();
        txtPersonEmail = new javax.swing.JTextField();
        txtPersonAddress = new javax.swing.JTextField();
        txtEmergency = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();

        lblPersonID.setText("Person ID");

        lblPersonName.setText("Name");

        lblAge.setText("Age");

        lblGender.setText("Gender");

        lblPhone.setText("Phone");

        lblEmail.setText("Email");

        lblAddress.setText("Address");

        lblEmergency.setText("Emergency Contact");

        submitAddPerson.setText("SUBMIT");
        submitAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddPersonActionPerformed(evt);
            }
        });

        txtPersonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonIDActionPerformed(evt);
            }
        });

        txtEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitAddPerson)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPersonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPersonID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPersonID)
                            .addComponent(txtPersonName)
                            .addComponent(txtPersonAge)
                            .addComponent(txtPersonPhone)
                            .addComponent(txtPersonEmail)
                            .addComponent(txtPersonAddress)
                            .addComponent(txtEmergency)
                            .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonID)
                    .addComponent(txtPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonName)
                    .addComponent(txtPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(txtPersonPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtPersonAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmergency)
                    .addComponent(txtEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitAddPerson)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonIDActionPerformed
    
    
    public PersonData addNewPerson(PersonData person){
      return  perHis.addNewData();
    }
    
    private void txtEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyActionPerformed

        public boolean validateData() {
            
        if (!txtPersonID.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(this, "Enter proper ID");
        }

        if (txtPersonName.getText().length() < 2 || !txtPersonName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper name");
            return false;
        }
        
        if (!txtPersonAge.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper age");
            return false;
        }
        
        if (!txtGender.getText().matches("^male$|^female$")){
            JOptionPane.showMessageDialog(this, "Enter proper gender");
            return false;
        }
         
        if (!txtPersonPhone.getText().matches("[0-9]+")||txtPersonPhone.getText().length()!=10) {
            JOptionPane.showMessageDialog(this, "Enter proper phone number");
            return false;
        }

        if (txtPersonAddress.getText().length() < 2 || !txtPersonAddress.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper address");
            return false;
        }
        
        if (!txtEmergency.getText().matches("[0-9]+")||txtEmergency.getText().length()!=10) {
            JOptionPane.showMessageDialog(this, "Enter proper emergency contact phone number");
            return false;
        }

        return true;
    }
    
    private void submitAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddPersonActionPerformed
        // TODO add your handling code here:
        if(txtPersonID.getText().equals("")||txtPersonName.getText().equals("")||txtPersonAge.getText().equals("")||txtGender.getText().equals("")||txtPersonPhone.getText().equals("")||
               txtPersonEmail.getText().equals("")|| txtPersonAddress.getText().equals("")|| txtEmergency.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Please fill all the information");
            
        }
        else if(validateData()){
            int Id=Integer.parseInt(txtPersonID.getText().trim());
            String name=txtPersonName.getText();
            int age=Integer.parseInt(txtPersonAge.getText().trim());
            String gender=txtGender.getText();
            String phone=txtPersonPhone.getText();
            String email=txtPersonEmail.getText();
            String address=txtPersonAddress.getText();
            String emergency=txtEmergency.getText();
            
            PersonData pd= perHis.addNewData();
            pd.setPersonID(Id);
            pd.setName(name);
            pd.setAge(age);
            pd.setGender(gender);
            pd.setPhone(phone);
            pd.setEmail(email);
            pd.setAddress(address);
            pd.setEmergency_contact(emergency);
            
            JOptionPane.showMessageDialog(this,"New Person Data Created");
            txtPersonID.setText("");
            txtPersonName.setText("");
            txtPersonAge.setText("");
            txtPersonEmail.setText("");
            txtGender.setText("");
            txtPersonPhone.setText("");
            txtPersonAddress.setText("");
            txtEmergency.setText("");
            
            
        }


    }//GEN-LAST:event_submitAddPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JButton submitAddPerson;
    private javax.swing.JTextField txtEmergency;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPersonAddress;
    private javax.swing.JTextField txtPersonAge;
    private javax.swing.JTextField txtPersonEmail;
    private javax.swing.JTextField txtPersonID;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtPersonPhone;
    // End of variables declaration//GEN-END:variables


    
    
}
