/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CommunityData;
import model.CommunityHistory;

/**
 *
 * @author movvakodandram
 */
public class EditCommunity extends javax.swing.JPanel {

    /**
     * Creates new form EditCommunity
     */
    CommunityHistory comHis;
    
    public EditCommunity(CommunityHistory comHis) {
        initComponents();
        this.comHis=comHis;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        commTable = new javax.swing.JTable();
        txtCommZip1 = new javax.swing.JTextField();
        submitVIewComm = new javax.swing.JButton();
        lblCommName1 = new javax.swing.JLabel();
        lblCommZip1 = new javax.swing.JLabel();
        txtCommName1 = new javax.swing.JTextField();
        submitUpdateComm = new javax.swing.JButton();
        submitDeleteComm = new javax.swing.JButton();

        commTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Community Object", "Community Name", "Zip Code"
            }
        ));
        jScrollPane1.setViewportView(commTable);

        txtCommZip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommZip1ActionPerformed(evt);
            }
        });

        submitVIewComm.setText("VIEW");
        submitVIewComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVIewCommActionPerformed(evt);
            }
        });

        lblCommName1.setText("Community Name");

        lblCommZip1.setText("Zip Code");

        txtCommName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommName1ActionPerformed(evt);
            }
        });

        submitUpdateComm.setText("UPDATE");
        submitUpdateComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateCommActionPerformed(evt);
            }
        });

        submitDeleteComm.setText("DELETE");
        submitDeleteComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeleteCommActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitVIewComm)
                        .addGap(18, 18, 18)
                        .addComponent(submitUpdateComm)
                        .addGap(18, 18, 18)
                        .addComponent(submitDeleteComm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCommZip1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCommName1))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCommName1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtCommZip1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommName1)
                    .addComponent(txtCommName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommZip1)
                    .addComponent(txtCommZip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitVIewComm)
                    .addComponent(submitDeleteComm)
                    .addComponent(submitUpdateComm))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommZip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommZip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommZip1ActionPerformed

    private void txtCommName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommName1ActionPerformed

    private void submitDeleteCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDeleteCommActionPerformed
        // TODO add your handling code here:
            int selectedRowIndex=commTable.getSelectedRow();
            if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
                DefaultTableModel model= (DefaultTableModel) commTable.getModel();
                CommunityData selectedPerson=(CommunityData) model.getValueAt(selectedRowIndex,0 );
                comHis.deleteData(selectedPerson);
                
                JOptionPane.showMessageDialog(this, "Community Data deleted");
                
                populateTable();


    }//GEN-LAST:event_submitDeleteCommActionPerformed

    private void submitVIewCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVIewCommActionPerformed
        // TODO add your handling code here:
               int selectedRowIndex=commTable.getSelectedRow();
               if(selectedRowIndex<0){
               JOptionPane.showMessageDialog(this, "Please select a row to view");
               return;
        }
        
                DefaultTableModel model= (DefaultTableModel) commTable.getModel();
                CommunityData selectedPerson=(CommunityData) model.getValueAt(selectedRowIndex,0 );
                txtCommName1.setText(String.valueOf(selectedPerson.getcName()));
                txtCommZip1.setText(String.valueOf(selectedPerson.getZipCode()));

    }//GEN-LAST:event_submitVIewCommActionPerformed

    private void submitUpdateCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateCommActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex= commTable.getSelectedRow();
              if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Please select view/modify  for the row you want to update");
                      return;
                         }
              
               DefaultTableModel model= (DefaultTableModel) commTable.getModel();
               CommunityData cd=(CommunityData) model.getValueAt(selectedRowIndex, 0);
        
            for(CommunityData i: comHis.getCommunityhistory()){
              if(i.getcName()==cd.getcName()){
               
            i.setcName(txtCommName1.getText());
            i.setZipCode(txtCommZip1.getText());
        
            populateTable();

            }

            }

    }//GEN-LAST:event_submitUpdateCommActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable commTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCommName1;
    private javax.swing.JLabel lblCommZip1;
    private javax.swing.JButton submitDeleteComm;
    private javax.swing.JButton submitUpdateComm;
    private javax.swing.JButton submitVIewComm;
    private javax.swing.JTextField txtCommName1;
    private javax.swing.JTextField txtCommZip1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
           DefaultTableModel model= (DefaultTableModel) commTable.getModel();
        
        model.setRowCount(0);
        for (CommunityData cd : comHis.getCommunityhistory()){
            Object[] row= new Object[3];
            row[0]=cd;
            row[1]=cd.getcName();
            row[2]=cd.getZipCode();
            
            
            model.addRow(row);
            
        }
        
    }
}
