/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import static javax.swing.JTable.PrintMode.NORMAL;
import javax.swing.table.DefaultTableModel;
import model.PersonData;
import model.PersonHistory;

/**
 *
 * @author movvakodandram
 */
public class EditPerson extends javax.swing.JPanel {

    /**
     * Creates new form EditPerson
     */
    
    PersonHistory perHis;
    PersonData pd;
    
    public EditPerson(PersonHistory perHis) {
        initComponents();
        this.perHis=perHis;

        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerson = new javax.swing.JTable();
        lblEmergencyV = new javax.swing.JLabel();
        txtPersonIDV = new javax.swing.JTextField();
        txtPersonNameV = new javax.swing.JTextField();
        lblPersonIDV = new javax.swing.JLabel();
        txtPersonAgeV = new javax.swing.JTextField();
        lblPersonNameV = new javax.swing.JLabel();
        lblAgeV = new javax.swing.JLabel();
        lblGenderV = new javax.swing.JLabel();
        txtPersonPhoneV = new javax.swing.JTextField();
        lblPhoneV = new javax.swing.JLabel();
        txtPersonEmailV = new javax.swing.JTextField();
        lblEmailV = new javax.swing.JLabel();
        txtPersonAddressV = new javax.swing.JTextField();
        lblAddressV = new javax.swing.JLabel();
        txtEmergencyV = new javax.swing.JTextField();
        submitUpdatePerson = new javax.swing.JButton();
        submitDeletePerson = new javax.swing.JButton();
        submitVIewPerson = new javax.swing.JButton();
        txtGenderV = new javax.swing.JTextField();

        tablePerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Person Object", "Person ID", "Name", "Age", "Gender", "Phone", "Address", "Email", "Emergency Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePerson);

        lblEmergencyV.setText("Emergency Contact");

        txtPersonIDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonIDVActionPerformed(evt);
            }
        });

        txtPersonNameV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonNameVActionPerformed(evt);
            }
        });

        lblPersonIDV.setText("Person ID");

        lblPersonNameV.setText("Name");

        lblAgeV.setText("Age");

        lblGenderV.setText("Gender");

        lblPhoneV.setText("Phone");

        lblEmailV.setText("Email");

        lblAddressV.setText("Address");

        txtEmergencyV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyVActionPerformed(evt);
            }
        });

        submitUpdatePerson.setText("UPDATE");
        submitUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdatePersonActionPerformed(evt);
            }
        });

        submitDeletePerson.setText("DELETE");
        submitDeletePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeletePersonActionPerformed(evt);
            }
        });

        submitVIewPerson.setText("VIEW");
        submitVIewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVIewPersonActionPerformed(evt);
            }
        });

        txtGenderV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAgeV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonNameV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonIDV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGenderV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPersonAgeV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPersonNameV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPersonIDV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGenderV, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmergencyV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhoneV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddressV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPersonEmailV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtPersonPhoneV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmergencyV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPersonAddressV))
                .addGap(26, 26, 26))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(submitVIewPerson)
                .addGap(18, 18, 18)
                .addComponent(submitUpdatePerson)
                .addGap(18, 18, 18)
                .addComponent(submitDeletePerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonIDV)
                    .addComponent(txtPersonIDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmergencyV)
                    .addComponent(txtEmergencyV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonNameV)
                    .addComponent(txtPersonNameV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneV)
                    .addComponent(txtPersonPhoneV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgeV)
                    .addComponent(txtPersonAgeV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailV)
                    .addComponent(txtPersonEmailV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenderV)
                    .addComponent(lblAddressV)
                    .addComponent(txtPersonAddressV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitVIewPerson)
                    .addComponent(submitDeletePerson)
                    .addComponent(submitUpdatePerson))
                .addGap(0, 70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonIDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonIDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonIDVActionPerformed

    private void txtEmergencyVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyVActionPerformed

    private void submitDeletePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDeletePersonActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex=tablePerson.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
                DefaultTableModel model= (DefaultTableModel) tablePerson.getModel();
                PersonData selectedPerson=(PersonData) model.getValueAt(selectedRowIndex,0 );
                perHis.deleteData(selectedPerson);
                
                JOptionPane.showMessageDialog(this, "Person Data deleted");
                
                populateTable();




    }//GEN-LAST:event_submitDeletePersonActionPerformed

    private void txtPersonNameVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonNameVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonNameVActionPerformed

    private void submitVIewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVIewPersonActionPerformed
        // TODO add your handling code here:
               int selectedRowIndex=tablePerson.getSelectedRow();
               if(selectedRowIndex<0){
               JOptionPane.showMessageDialog(this, "Please select a row to view");
               return;
        }
        
                DefaultTableModel model= (DefaultTableModel) tablePerson.getModel();
                PersonData selectedPerson=(PersonData) model.getValueAt(selectedRowIndex,0);
                txtPersonIDV.setText(String.valueOf(selectedPerson.getPersonID()));
                txtPersonNameV.setText(selectedPerson.getName());                
                txtPersonAgeV.setText(String.valueOf(selectedPerson.getAge()));
                txtGenderV.setText(selectedPerson.getGender());
                txtPersonPhoneV.setText(selectedPerson.getPhone());
                txtPersonEmailV.setText(selectedPerson.getEmail());
                txtPersonAddressV.setText(selectedPerson.getAddress());
                txtEmergencyV.setText(String.valueOf(selectedPerson.getEmergency_contact()));
                

    }//GEN-LAST:event_submitVIewPersonActionPerformed

    private void txtGenderVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderVActionPerformed

    private void submitUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdatePersonActionPerformed
        // TODO add your handling code here:
             int selectedRowIndex= tablePerson.getSelectedRow();
              if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Please select view/modify  for the row you want to update");
                      return;
                         }
              
               DefaultTableModel model= (DefaultTableModel) tablePerson.getModel();
               PersonData pd=(PersonData) model.getValueAt(selectedRowIndex, 0);
        
        for(PersonData i: perHis.getPersonhistory()){
            if(i.getPersonID()==pd.getPersonID()){

            i.setPersonID(Integer.parseInt(txtPersonIDV.getText()));
            i.setName(txtPersonNameV.getText());
            i.setAge(Integer.parseInt(txtPersonAgeV.getText()));
            i.setGender(txtGenderV.getText());
            i.setPhone(txtPersonPhoneV.getText());
            i.setEmail(txtPersonEmailV.getText());
            i.setAddress(txtPersonAddressV.getText());
            i.setEmergency_contact(txtEmergencyV.getText());
            
            populateTable();


            }
        }

    }//GEN-LAST:event_submitUpdatePersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddressV;
    private javax.swing.JLabel lblAgeV;
    private javax.swing.JLabel lblEmailV;
    private javax.swing.JLabel lblEmergencyV;
    private javax.swing.JLabel lblGenderV;
    private javax.swing.JLabel lblPersonIDV;
    private javax.swing.JLabel lblPersonNameV;
    private javax.swing.JLabel lblPhoneV;
    private javax.swing.JButton submitDeletePerson;
    private javax.swing.JButton submitUpdatePerson;
    private javax.swing.JButton submitVIewPerson;
    private javax.swing.JTable tablePerson;
    private javax.swing.JTextField txtEmergencyV;
    private javax.swing.JTextField txtGenderV;
    private javax.swing.JTextField txtPersonAddressV;
    private javax.swing.JTextField txtPersonAgeV;
    private javax.swing.JTextField txtPersonEmailV;
    private javax.swing.JTextField txtPersonIDV;
    private javax.swing.JTextField txtPersonNameV;
    private javax.swing.JTextField txtPersonPhoneV;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
            
        DefaultTableModel model= (DefaultTableModel) tablePerson.getModel();
        
        model.setRowCount(0);
        for (PersonData pd : perHis.getPersonhistory()){
            Object[] row= new Object[9];
            row[0]=pd;
            row[1]=pd.getPersonID();
            row[2]=pd.getName();
            row[3]=pd.getAge();
            row[4]=pd.getGender();
            row[5]=pd.getPhone();
            row[6]=pd.getEmail();
            row[7]=pd.getAddress();
            row[8]=pd.getEmergency_contact();
            
            model.addRow(row);
            
        }
        
    }




}
