/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DoctorHistory;

/**
 *
 * @author movvakodandram
 */
public class HospitalAdmin extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdmin
     */
    DoctorHistory drhis;
    public HospitalAdmin() {
        initComponents();
        drhis = new DoctorHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        hsptAddDr = new javax.swing.JButton();
        hsptEditDr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        hsptAddDr.setText("ADD DOCTOR");
        hsptAddDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsptAddDrActionPerformed(evt);
            }
        });

        hsptEditDr.setText("EDIT DOCTOR");
        hsptEditDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsptEditDrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hsptAddDr)
                    .addComponent(hsptEditDr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(hsptAddDr)
                .addGap(121, 121, 121)
                .addComponent(hsptEditDr)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        splitPane2.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        splitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hsptAddDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsptAddDrActionPerformed
        // TODO add your handling code here:
        AddDoctor adddr = new AddDoctor(drhis);
        splitPane2.setRightComponent(adddr);
    }//GEN-LAST:event_hsptAddDrActionPerformed

    private void hsptEditDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsptEditDrActionPerformed
        // TODO add your handling code here:
        EditDoctor editdr = new EditDoctor(drhis);
        splitPane2.setRightComponent(editdr);
    }//GEN-LAST:event_hsptEditDrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hsptAddDr;
    private javax.swing.JButton hsptEditDr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitPane2;
    // End of variables declaration//GEN-END:variables
}
