/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmployeeData;
import model.EmployeeHistory;

/**
 *
 * @author movvakodandram
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubmitJPanel
     */
EmployeeHistory history;
    
    public SearchJPanel(EmployeeHistory history) {
        
        initComponents();
        
        this.history=history;
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        lblView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        lblView.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("Search Employee");

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Id", "Age", "Gender", "Start", "Level", "Info", "Title", "Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jLabel1.setText("Keyword:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
/*
            List <EmployeeData> search=new ArrayList<>();
            String keyWord=txtSearch.getText();
           for(EmployeeData ed: history.getHistory()){
               if((ed.getName().contains(keyWord)|| ed.getGender().contains(keyWord)||ed.getLevel().contains(keyWord)||ed.getStartDate().contains(keyWord)||ed.getEmailAddress().contains(keyWord)||ed.getTeamInfo().contains(keyWord)||ed.getPositionTitle().contains(keyWord))){
                   
                   search.addData(ed);
                   
               }
           }
           
           SearchTable(search);
            */
          

      /*  String name=txtName.getText();
        int employeeId=Integer.parseInt(txtId.getText().trim());
        int age=Integer.parseInt(txtAge.getText().trim());
        String gender=txtGender.getText();
        String startDate=txtDate.getText();
        String level=txtLevel.getText();
        String teamInfo=txtInfo.getText();
        String positionTitle=txtPos.getText();
        int cellPhoneNumber=Integer.parseInt(txtNum.getText().trim());
        String emailAddress=txtEmail.getText();

        model.setValueAt(name, dataTable.getSelectedRow(), 0);
        model.setValueAt(employeeId, dataTable.getSelectedRow(), 1);
        model.setValueAt(age, dataTable.getSelectedRow(), 2);
        model.setValueAt(gender, dataTable.getSelectedRow(), 3);
        model.setValueAt(startDate, dataTable.getSelectedRow(), 4);
        model.setValueAt(level, dataTable.getSelectedRow(), 5);
        model.setValueAt(teamInfo, dataTable.getSelectedRow(), 6);
        model.setValueAt(positionTitle, dataTable.getSelectedRow(), 7);
        model.setValueAt(cellPhoneNumber, dataTable.getSelectedRow(), 8);
        model.setValueAt(emailAddress, dataTable.getSelectedRow(), 9);

        JOptionPane.showMessageDialog(this,"Data Updated");
        txtName.setText("");
        txtAge.setText("");
        txtDate.setText("");
        txtEmail.setText("");
        txtGender.setText("");
        txtId.setText("");
        txtInfo.setText("");
        txtLevel.setText("");
        txtNum.setText("");
        txtPhoto.setText("");
        txtPos.setText("");  */

    }//GEN-LAST:event_searchButtonActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblView;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
 private void populateTable() {
            
        DefaultTableModel model= (DefaultTableModel) dataTable.getModel();
        
        model.setRowCount(0);
        for (EmployeeData ed : history.getHistory()){
            Object[] row= new Object[10];
            row[0]=ed;
            row[1]=ed.getEmployeeId();
            row[2]=ed.getAge();
            row[3]=ed.getGender();
            row[4]=ed.getStartDate();
            row[5]=ed.getLevel();
            row[6]=ed.getTeamInfo();
            row[7]=ed.getPositionTitle();
            row[8]=ed.getCellPhoneNumber();
            row[9]=ed.getEmailAddress();
            
            model.addRow(row);
            
        }
        
    }


}
