/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author movvakodandram
 */
public class SystemAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdmin
     */
    public SystemAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        adminEditHospital = new javax.swing.JButton();
        adminAddCommunity = new javax.swing.JButton();
        AdminEditCommunity = new javax.swing.JButton();
        adminAddDoctor = new javax.swing.JButton();
        adminEditDoctor = new javax.swing.JButton();
        adminAddHospital = new javax.swing.JButton();
        adminAddPerson = new javax.swing.JButton();
        adminEditPatient = new javax.swing.JButton();
        adminEditPerson = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        adminEditHospital.setText("EDIT HOSPITAL");
        adminEditHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditHospitalActionPerformed(evt);
            }
        });

        adminAddCommunity.setText("ADD COMMUNITY");

        AdminEditCommunity.setText("EDIT COMMUNITY");
        AdminEditCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminEditCommunityActionPerformed(evt);
            }
        });

        adminAddDoctor.setText("ADD DOCTOR");

        adminEditDoctor.setText("EDIT DOCTOR");
        adminEditDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditDoctorActionPerformed(evt);
            }
        });

        adminAddHospital.setText("ADD HOSPITAL");
        adminAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddHospitalActionPerformed(evt);
            }
        });

        adminAddPerson.setText("ADD PERSON");
        adminAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminAddPersonActionPerformed(evt);
            }
        });

        adminEditPatient.setText("EDIT PATIENT");

        adminEditPerson.setText("EDIT PERSON");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminEditHospital)
                    .addComponent(adminAddCommunity)
                    .addComponent(AdminEditCommunity)
                    .addComponent(adminAddDoctor)
                    .addComponent(adminEditDoctor)
                    .addComponent(adminAddHospital)
                    .addComponent(adminAddPerson)
                    .addComponent(adminEditPatient)
                    .addComponent(adminEditPerson))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(adminAddHospital)
                .addGap(18, 18, 18)
                .addComponent(adminEditHospital)
                .addGap(18, 18, 18)
                .addComponent(adminAddCommunity)
                .addGap(18, 18, 18)
                .addComponent(AdminEditCommunity)
                .addGap(18, 18, 18)
                .addComponent(adminAddDoctor)
                .addGap(18, 18, 18)
                .addComponent(adminEditDoctor)
                .addGap(18, 18, 18)
                .addComponent(adminAddPerson)
                .addGap(18, 18, 18)
                .addComponent(adminEditPerson)
                .addGap(18, 18, 18)
                .addComponent(adminEditPatient)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        splitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        splitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminAddHospitalActionPerformed

    private void adminEditHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditHospitalActionPerformed

    private void adminEditDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditDoctorActionPerformed

    private void adminAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminAddPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminAddPersonActionPerformed

    private void AdminEditCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEditCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminEditCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminEditCommunity;
    private javax.swing.JButton adminAddCommunity;
    private javax.swing.JButton adminAddDoctor;
    private javax.swing.JButton adminAddHospital;
    private javax.swing.JButton adminAddPerson;
    private javax.swing.JButton adminEditDoctor;
    private javax.swing.JButton adminEditHospital;
    private javax.swing.JButton adminEditPatient;
    private javax.swing.JButton adminEditPerson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitPane1;
    // End of variables declaration//GEN-END:variables
}
